version: "3"

services:
  postgresqldb:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce-db-test

